stages:
  - test

default:
  image:
    name: hub.adsw.io/library/trigger_pipeline_by_webhook:3.16.2-x64
    entrypoint: [""]
  tags:
    - k8s

Test:
  stage: test
  script:
    - echo "TEST"
  rules:
    - if: $CI_PIPELINE_SOURCE == "external_pull_request_event"
    - if: $CI_PIPELINE_SOURCE == "trigger"

Test2:
  stage: test
  script:
    - echo "TEST2"
  rules:
    - if: $CI_COMMIT_BRANCH
